import { isDataModel } from '../schema/data-models.ts';
import { MAX_DIAGRAM_FILE_BYTES } from './diagram-files.ts';
import type { DiagramContext, DiagramGraph } from './diagram-graph.ts';
import { diagramType } from './diagram-types.ts';

export const MAX_DIAGRAM_NODES = 160;
export const MAX_DIAGRAM_EDGES = 320;
export const MAX_DIAGRAM_GROUPS = 16;

function tuple(value: unknown, min: number, max: number, where: string): string[] {
  if (!Array.isArray(value) || value.length < min || value.length > max || !value.every(item => typeof item === 'string')) {
    throw new Error(`${where} must be an array of ${min === max ? min : `${min}–${max}`} strings. No coordinates or styles are accepted.`);
  }
  return value as string[];
}
function identifier(value: string, where: string): string {
  if (!/^[A-Za-z][A-Za-z0-9_.-]{0,79}$/.test(value)) throw new Error(`${where}: use a local ID starting with a letter, followed by letters, digits, dots, underscores or hyphens (max 80 characters).`);
  return value;
}
function label(value: string, context: DiagramContext, where: string): string {
  if (value.length > 500 || /[\u0000-\u0008\u000b\u000c\u000e-\u001f\ufffe\uffff]/u.test(value)) throw new Error(`${where}: label must be valid plain text of at most 500 characters.`);
  const known = context.labels.get(value);
  if (known) return known;
  if (value.startsWith('@') || context.prefixes.some(prefix => value.startsWith(prefix))) {
    throw new Error(`${where}: "${value}" is not a current named reference. Correct the saved link or copy a fresh diagram prompt.`);
  }
  return value.trim();
}
function list(value: unknown, limit: number, where: string): unknown[] {
  if (!Array.isArray(value)) throw new Error(`${where} must be an array.`);
  if (value.length > limit) throw new Error(`${where} exceeds the ${limit}-item diagram limit. Split the diagram into smaller figures.`);
  return value;
}

export function parseDiagramResponse(response: string, context: DiagramContext, expectedType?: string): DiagramGraph {
  if (new TextEncoder().encode(response).byteLength > MAX_DIAGRAM_FILE_BYTES) throw new Error('The pasted response exceeds the 2 MB per-file limit.');
  const fenced = /^\s*```dsrs-diagram\s*\r?\n([\s\S]*?)\r?\n```\s*$/.exec(response);
  if (!fenced) throw new Error('Paste exactly one fenced dsrs-diagram JSON block, with no text before or after it.');
  let input: unknown;
  try { input = JSON.parse(fenced[1]!); }
  catch { throw new Error('The dsrs-diagram block is not valid JSON. Check quotes, commas and brackets, or ask the AI to correct the block.'); }
  if (!isDataModel(input) || Object.keys(input).some(key => !['t', 'g', 'n', 'e'].includes(key)) || typeof input.t !== 'string') {
    throw new Error('The graph must be an object with only t, g, n and e. Layout, XML and styles are generated by the application.');
  }
  const type = diagramType(input.t);
  if (expectedType && type.id !== expectedType) throw new Error(`This field expects "${expectedType}", but the response contains "${type.id}".`);
  const used = new Set<string>();
  function claim(value: string, where: string): string {
    const id = identifier(value, where);
    if (used.has(id)) throw new Error(`${where}: duplicate local ID "${id}".`);
    used.add(id); return id;
  }
  const groups = list(input.g, MAX_DIAGRAM_GROUPS, 'g').map((value, i) => {
    const row = tuple(value, 2, 2, `g[${i}]`);
    const resolved = label(row[1]!, context, `g[${i}] label`);
    if (!resolved) throw new Error(`g[${i}] needs a group label.`);
    return { id: claim(row[0]!, `g[${i}]`), label: resolved };
  });
  const nodes = list(input.n, MAX_DIAGRAM_NODES, 'n').map((value, i) => {
    const row = tuple(value, 3, 4, `n[${i}]`);
    if (!type.nodeKinds.includes(row[1]!)) throw new Error(`n[${i}]: unsupported node kind "${row[1]}". Use ${type.nodeKinds.join(', ')}.`);
    const group = row[3] || '';
    if (group && !groups.some(entry => entry.id === group)) throw new Error(`n[${i}]: unknown group "${group}".`);
    const resolved = label(row[2]!, context, `n[${i}] label`);
    if (!resolved && !['start', 'end', 'fork', 'join', 'merge'].includes(row[1]!)) throw new Error(`n[${i}] needs a semantic label or canonical record ID.`);
    return { id: claim(row[0]!, `n[${i}]`), kind: row[1]!, label: resolved, group };
  });
  if (!nodes.length) throw new Error('The diagram has no nodes. Supply supported diagram semantics first.');
  const edges = list(input.e, MAX_DIAGRAM_EDGES, 'e').map((value, i) => {
    const row = tuple(value, 2, 4, `e[${i}]`);
    for (const id of row.slice(0, 2)) if (!nodes.some(node => node.id === id)) throw new Error(`e[${i}]: unknown node "${id}".`);
    const kind = row[2] || type.defaultEdge;
    if (!type.edgeKinds.includes(kind)) throw new Error(`e[${i}]: unsupported edge kind "${kind}". Use ${type.edgeKinds.join(', ')}.`);
    return { from: row[0]!, to: row[1]!, kind, label: label(row[3] || '', context, `e[${i}] label`) };
  });
  const graph = { type: type.id, groups, nodes, edges };
  const signatures = edges.map(edge => JSON.stringify([edge.from, edge.to, edge.kind, edge.label]));
  if (new Set(signatures).size !== signatures.length) throw new Error('The graph contains duplicate edges. Keep each semantic connection once.');
  type.validate(graph);
  return graph;
}
