import { records, text, optional } from '../../planning/schema-helpers.ts';
export const benefitDriversSection = records('benefit-drivers', 'Benefits', 'One supported improvement per entry. Quantify only when evidence supports it.', 'benefits', 'CBA-BEN-', 'name', [
  { key: "name", label: "Benefit name", type: "text", default: "", columns: "col-md-7", aiHint: "Use a concise business outcome name, such as Increased online bookings or Reduced printing cost." },
  { key: "benefitType", label: "Can this benefit be supported with a financial amount?", type: "select", default: "Quantified tangible", columns: "col-md-5", options: [{ value: "Quantified tangible", label: "Yes — calculate it in money" }, { value: "Intangible or non-monetized", label: "No — describe it without money" }], aiHint: "Quantify only when defensible financial evidence exists." },
  { key: "description", label: "Benefit description and beneficiary", type: "textarea", rows: 2, default: "", columns: "col-md-8", aiHint: "Explain the outcome, who receives it, and how it follows from the System Request without repeating the calculation." , optional: true },
  { key: "calculationMethod", label: "How should the annual benefit be calculated?", type: "select", default: "Baseline vs target", columns: "col-md-4", options: [{ value: "Baseline vs target", label: "Compare current value with expected value" }, { value: "Direct annual benefit", label: "Enter a trusted annual amount directly" }], showWhen: { key: "benefitType", equals: "Quantified tangible" }, aiHint: "Use baseline versus target when operational drivers are available; otherwise use a directly sourced annual benefit." },
  { key: "benefitDirection", label: "What kind of improvement creates the benefit?", type: "select", default: "Target less baseline", columns: "col-md-4", options: [{ value: "Target less baseline", label: "An increase creates value" }, { value: "Baseline less target", label: "A reduction creates savings" }], showWhen: { all: [{ key: "benefitType", equals: "Quantified tangible" }, { key: "calculationMethod", equals: "Baseline vs target" }] }, aiHint: "Choose An increase creates value for incremental revenue or output, or A reduction creates savings for savings or reductions. Return the displayed choice label." },
  { key: "baselineQuantity", label: "Current annual quantity", type: "number", default: "", min: 0, step: "any", columns: "col-md-4", showWhen: { all: [{ key: "benefitType", equals: "Quantified tangible" }, { key: "calculationMethod", equals: "Baseline vs target" }] }, aiHint: "Use an annual volume such as customers, transactions, units, hours, or occurrences." },
  { key: "baselineUnitValue", label: "Current value per unit", type: "number", default: "", min: 0, step: "any", columns: "col-md-4", showWhen: { all: [{ key: "benefitType", equals: "Quantified tangible" }, { key: "calculationMethod", equals: "Baseline vs target" }] }, aiHint: "Enter currency value per unit using the model currency." },
  { key: "baselineFactor", label: "Current value kept (%)", type: "number", default: 100, min: 0, max: 100, step: 0.01, columns: "col-md-4", showWhen: { all: [{ key: "benefitType", equals: "Quantified tangible" }, { key: "calculationMethod", equals: "Baseline vs target" }] }, aiHint: "Enter the percentage retained as value after margin, participation, external share, or another supported factor; use 100 when none applies." },
  { key: "targetQuantity", label: "Expected annual quantity", type: "number", default: "", min: 0, step: "any", columns: "col-md-4", showWhen: { all: [{ key: "benefitType", equals: "Quantified tangible" }, { key: "calculationMethod", equals: "Baseline vs target" }] }, aiHint: "Enter the supported target annual volume after the proposed change." },
  { key: "targetUnitValue", label: "Expected value per unit", type: "number", default: "", min: 0, step: "any", columns: "col-md-4", showWhen: { all: [{ key: "benefitType", equals: "Quantified tangible" }, { key: "calculationMethod", equals: "Baseline vs target" }] }, aiHint: "Enter target currency value per unit; preserve the baseline value if pricing is unchanged." },
  { key: "targetFactor", label: "Expected value kept (%)", type: "number", default: 100, min: 0, max: 100, step: 0.01, columns: "col-md-4", showWhen: { all: [{ key: "benefitType", equals: "Quantified tangible" }, { key: "calculationMethod", equals: "Baseline vs target" }] }, aiHint: "Enter the supported target retained percentage on the same basis as the baseline factor." },
  { key: "directAnnualBenefit", label: "Benefit in one full operating year", type: "number", default: "", min: 0, step: "any", columns: "col-md-8", showWhen: { all: [{ key: "benefitType", equals: "Quantified tangible" }, { key: "calculationMethod", equals: "Direct annual benefit" }] }, aiHint: "Enter a directly sourced annual amount, not a five-year total." },
  { key: "realizationPattern", label: "How quickly will the benefit appear?", type: "select", default: "Linear ramp to target", columns: "col-md-4", options: [{ value: "Linear ramp to target", label: "Increase gradually to full value" }, { value: "Full benefit from start year", label: "Reach full value immediately" }, { value: "Custom yearly amounts", label: "Enter a different amount for each year" }], showWhen: { key: "benefitType", equals: "Quantified tangible" }, aiHint: "Choose how the annual benefit becomes available over the analysis period." },
  { key: "startYear", label: "First year this benefit appears", type: "number", default: 1, min: 1, max: 10, step: 1, columns: "col-md-4", showWhen: { all: [{ key: "benefitType", equals: "Quantified tangible" }, { key: "realizationPattern", in: ["Linear ramp to target", "Full benefit from start year"] }] }, aiHint: "Use the first year in which this benefit contributes value." },
  { key: "targetYear", label: "Year the full benefit is reached", type: "number", default: 5, min: 1, max: 10, step: 1, columns: "col-md-4", showWhen: { all: [{ key: "benefitType", equals: "Quantified tangible" }, { key: "realizationPattern", equals: "Linear ramp to target" }] }, aiHint: "Use the year in which the full annual benefit is expected; the model ramps evenly from the start year." },
  { key: "annualValues", label: "Custom annual benefit amounts", type: "period-values", default: [], min: 0, step: "any", columns: "col-12", showWhen: { all: [{ key: "benefitType", equals: "Quantified tangible" }, { key: "realizationPattern", equals: "Custom yearly amounts" }] }, aiHint: "Enter one supported benefit amount for every analysis year; use zero where no value occurs." },
  { key: 'sourceIds', label: 'Supporting sources', type: 'record-links', default: '', reference: { dataPath: ['costBenefitAnalysis', 'sources'], displayId: { prefix: 'CBA-SRC-', padding: 3 }, labelField: 'item' }, aiHint: 'Select existing evidence records by name; return exact IDs only.' },
  optional(text('assumptions', 'Estimate basis and uncertainty', { placeholder: 'Include quantities, units, exclusions or assumptions needed to understand the estimate. Do not repeat a source citation.' }))
], { itemLabel: 'Benefit', addLabel: 'Add benefit' });
