import { records, text, optional } from '../../planning/schema-helpers.js';
export const ongoingCostsSection = records('ongoing-costs', 'Ongoing costs', 'Choose a schedule; only its relevant amount and timing fields need answers.', 'ongoingCosts', 'CBA-OGC-', 'name', [
  { key: "name", label: "Cost name", type: "text", default: "", columns: "col-md-7", aiHint: "Use a concise name for the operating or lifecycle cost." },
  { key: "scheduleType", label: "How does this cost repeat?", type: "select", default: "Flat annual", columns: "col-md-4", options: [{ value: "Flat annual", label: "Same amount every year" }, { value: "Annual growth", label: "Amount grows each year" }, { value: "Recurring interval", label: "Repeats every few years" }, { value: "Custom yearly amounts", label: "Enter each year's amount" }], aiHint: "Choose the pattern that matches the estimate and timing evidence." },
  { key: "amount", label: "Starting or recurring amount", type: "number", default: "", min: 0, step: "any", columns: "col-md-4", showWhen: { key: "scheduleType", in: ["Flat annual", "Annual growth", "Recurring interval"] }, aiHint: "Enter the positive amount in model currency for the first applicable occurrence." },
  { key: "startYear", label: "Start year", type: "number", default: 1, min: 1, max: 10, step: 1, columns: "col-md-4", showWhen: { key: "scheduleType", in: ["Flat annual", "Annual growth", "Recurring interval"] }, aiHint: "Enter the first analysis year in which the cost occurs." },
  { key: "endYear", label: "End year", type: "number", default: 5, min: 1, max: 10, step: 1, columns: "col-md-4", showWhen: { key: "scheduleType", in: ["Flat annual", "Annual growth"] }, aiHint: "Enter the final analysis year in which the cost occurs." },
  { key: "annualGrowthRate", label: "Annual growth (%)", type: "number", default: 0, min: -100, max: 1000, step: 0.01, columns: "col-md-4", showWhen: { key: "scheduleType", equals: "Annual growth" }, aiHint: "Enter the sourced annual escalation percentage; do not assume inflation without documenting it." },
  { key: "recurrenceInterval", label: "Repeat every N years", type: "number", default: 3, min: 1, max: 10, step: 1, columns: "col-md-4", showWhen: { key: "scheduleType", equals: "Recurring interval" }, aiHint: "Enter the supported useful life or replacement interval." },
  { key: "annualValues", label: "Custom annual cost amounts", type: "period-values", default: [], min: 0, step: "any", columns: "col-12", showWhen: { key: "scheduleType", equals: "Custom yearly amounts" }, aiHint: "Enter one cost for every analysis year; use zero in years with no cost." },
  { key: 'sourceIds', label: 'Supporting sources', type: 'record-links', default: '', reference: { dataPath: ['costBenefitAnalysis', 'sources'], displayId: { prefix: 'CBA-SRC-', padding: 3 }, labelField: 'item' }, aiHint: 'Select existing evidence records by name; return exact IDs only.' },
  optional(text('assumptions', 'Estimate basis and uncertainty', { placeholder: 'Include quantities, units, exclusions or assumptions needed to understand the estimate. Do not repeat a source citation.' }))
], { itemLabel: 'Ongoing cost', addLabel: 'Add ongoing cost' });
